### PR TITLE
Submit IIP-3: Voting discrimination

### PR DESCRIPTION
**Pull request by ZenMaster420**

### CODE REVIEW

**Comment by midenaio** [comment]
@ZenMaster420 could you also update the [IIPs list](https://idena-docs-git-fork-zenmaster420-main-idena.vercel.app/docs/iip/iips/)

**Comment by ZenMaster420** [comment]
Will update later today!

**Comment by ZenMaster420** [comment]
Updated IIP list.
Marked the IIP as ready for Review since discussions on GitHub and Discord regarding the proposal stopped and the idea got to its final form with contributions from the community.

**Comment by midenaio** [comment]
Thank you, @ZenMaster420. I'll post our feedback on the proposal on github discussion as soon as possible.

**Pull request merged**
