### PR TITLE
Submit IIP-6: Change the requirements needed to reach quorum in Oracle Votings

### PR DESCRIPTION
**Pull request by Zen-44**

### CODE REVIEW

**Comment by midenaio** [comment]
@Zen-44 thank you for the Oracle voting improvement proposal. However, there is an inconsistency in the proposed solution.

Let’s consider a corner case when the quorum is 100% and the committee size is the entire network. In the proposed design 100% quorum is not achievable even if the entire network votes as the network has more than 0 discriminated accounts.

**Comment by Zen-44** [comment]
@midenaio I would propose calculating the quorum as a percent of the total number of non-discriminated users instead of a percentage of the entire committee size. This can lead to another case where if you set the quorum to 100% and someone gets discriminated, the quorum won't be reachable. This is similar to setting an oracle voting to 100% quorum and having the entire network as the committee: anyone terminating their identity would make the quorum impossible to reach.

**Comment by Zen-44** [comment]
@midenaio Thanks for the feedback. It becomes apparent that a hard requirement relating to this issue is really hard to implement due to the random nature of committees. I wrote a soft fix that doesn't eliminate the problem completely but allows for edge cases to acquire enough votes (most notably for ad review oracles that usually don't have many people voting).

**Comment by Zen-44** [comment]
> @midenaio Thanks for the feedback. It becomes apparent that a hard requirement relating to this issue is really hard to implement due to the random nature of committees. I wrote a soft fix that doesn't eliminate the problem completely but allows for edge cases to acquire enough votes (most notably for ad review oracles that usually don't have many people voting).
> 
> I would love some more feedback. Would it help prolonging oracles more than one time (as proposed in the latest change)? Or is there any other solution for this?

I think it would also be a good addition to have clients display an approximation of how many committee members will be discriminated when creating an oracle. I think it would benefit setting authors' expectations.

**Pull request closed without merging**
